# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Garajau
author:
  name: Daniel Garajau
  email: daniel@garajau.com.br
  url: "https://garajau.com.br" # the base hostname & protocol for your site
description: >
  Yet another software engineer. I write about technologies and
  its ecosystem. I love open-source and talk about stuff I want
  to share with the world. I hope somebody can enjoy it.

# URL settings
baseurl: # the subpath of your site, e.g. /blog
url: "https://garajau.com.br" # the base hostname & protocol for your site
permalink: "/:year/:month/:title"
paginate_path: /page/:num

exclude:
  - README.md
  - LICENSE
  - CNAME

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
paginate: 5

# Google Analytics
google_analytics: UA-39558114-1
