# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Garajau
email: daniel@garajau.com.br
description: >
  Yet another software engineer. I write about technologies and
  its ecosystem. I love open-source and talk about stuff I want
  to share with the world. I hope somebody can enjoy it.
baseurl: # the subpath of your site, e.g. /blog
header-img: img/home-bg.jpg
url: "https://garajau.com.br" # the base hostname & protocol for your site
twitter_username: kriansa
github_username: kriansa
linkedin_username: kriansa
permalink: "/:year/:month/:title"
paginate_path: /page/:num

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

# Build settings
highlighter: pygments
paginate: 10
